### ISSUE TITLE
Structures not spawning with turned off biome in config - Affects VANILLA STRUCTURES

### ISSUE THREAD

**Issue by zachsai** [Glitchfiend/BiomesOPlenty#1991]
### What's the issue you encountered?

Structures, such as the dungeon crawl structure, cannot be located and do not spawn when you toggle any of the biomes to off, I tested with the first biome in the list to off, then BOOM. Structure cannot be located.

### How can the issue be reproduced?

biomes o plenty, terrablender, dungeon crawl
alter the config to turn off a biome
do a /locate of the dungeon crawl structure. It wont show up. Reset configs and recreate world, it shows up

### Mod Version

16.0.0.107

**Comment by kuba26038** [comment]
having the same issue with both dungeons plus and valheisa structures, some structures generate, some don't, and whenever i enable certain biomes, some of the missing structures start appearing again.

**Comment by Forstride** [comment]
I believe this was already fixed at some point, but the issue was never closed.

**Comment by kuba26038** [comment]
i doubt it, as the tower structure from dungeons plus still doesn't generate, unless i regenerate the biomes of plenty config or i delete the mod.

**Comment by Adubbz** [comment]
You're probably using an old version of the mod.

**Comment by kuba26038** [comment]
well, if the 1.19.2's newest version is old, then yes. was the fix not backported to the only modwise active version of 1.19?

**Comment by Adubbz** [comment]
This is fixed in 1.19.3 as a result of significant codebase changes made specifically for that version. We are no longer maintaining 1.19.2.

**Comment by kuba26038** [comment]
sucks to be us

**Comment by kuba26038** [comment]
i'm honest here- leaving such a devastating bug in such an active modding version seems like a totally misdirected decision on your part. maybe fixing it wouldn't need a total revamp of the code and could be fixed even without backporting all of the code changes from 1.19.3?

**Comment by Adubbz** [comment]
If someone wishes to fix this for 1.19.2 they are welcome to submit a pull request, the source for that version is public. We have no interest in developing for whatever arbitrary old Minecraft version others decide to sit on for a prolonged period of time, on top of the latest version of the game. 
Biome mods have consistently faced the brunt of Mojang’s code changes across versions, to the point where our code base is substantially different. This holds true for 1.19.2 to 1.19.3, despite the misleading numbering. Re-fixing bugs that have already been fixed in different ways in newer versions is not how I want to spend my limited time modding. If we concern ourselves with which version of the hour others find popular, we’d be still developing our mods for 1.4.7, 1.6.4, 1.7.10, 1.12.2, 1.16.5, 1.18.2 and 1.19.2. That’s simply not viable.
