### ISSUE TITLE
[1.7.10] Disabled (null) biomes still registered to Biome Dictionary

### ISSUE THREAD

**Issue by ReikaKalseki** [Glitchfiend/BiomesOPlenty#567]
As per the title, BOP still tries to register disabled (ID=-1) biomes to the Biome Dictionary, triggering an NPE during load.

The easiest fix is to edit `addBiomesToDictionary` and replace all the calls to `BiomeDictionary.registerBiomeType` with a method delegate that checks `biome != null` then passes it on.

EDIT:
I will PR the fix.

EDIT 2: There are multiple other similar issues, including in `disableRiver` and `BOPEntities.registerEntities`. The PR has not been updated because I am going to bed. :P

**Comment by Adubbz** [comment]
Hrm, for some reason I thought I never added disabling biome id usage to 1.7, which is probably why some things account for it and others don't. Fortunately this shouldn't be a problem in 1.8, but i'm happy to accept any fixes you want to make to 1.7.

**Comment by ReikaKalseki** [comment]
Does BoP build automatically like IC2, or would you have to manually release a new version with the fixes?

**Comment by Adubbz** [comment]
Should still build automatically for 1.7, building isonly be broken for 1.8.8 at this stage until I get in touch with the Forge guys about issues with the setup. Looks like ironchests and CodeChickenLib are experiencing similar issues. Scroll down on http://files.minecraftforge.net/BiomesOPlenty/ and you should see the new build

**Comment by Adubbz** [comment]
Ah, I think I see why the last one didn't come through, you submitted your last PR it to the BOP-1.7.10+2-2.0.x branch as opposed to BOP-1.7.10-2.1.x. An understandable mistake to make, admittedly I didn't even notice it myself.

**Comment by Adubbz** [comment]
Should be resolved now, a new build should be up in a few.

**Comment by ReikaKalseki** [comment]
My PR did not fix most of the other, similar issues, including the ones mentioned above, so the current release still suffers from them.
