### ISSUE TITLE
piston dupe bug with exception

### ISSUE THREAD

**Issue by meelock** [Glitchfiend/BiomesOPlenty#926]
Whenever I break a normal piston and pick it up I get two pistons instead of one, also i am using many other mods so i may need give you guys a list. There is also an exception that occurred whenever the dupe happens:

Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} to null on block minecraft:piston, it is not an allowed value
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} to null on block minecraft:piston, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:222) ~[art$a.class:?]
	at net.minecraft.block.BlockPistonBase.func_176203_a(BlockPistonBase.java:424) ~[arj.class:?]
	at biomesoplenty.common.handler.AchievementEventHandler.onBlockPlaced(AchievementEventHandler.java:191) ~[AchievementEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_222_AchievementEventHandler_onBlockPlaced_PlaceEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:151) ~[ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:811) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:144) ~[adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:493) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

#### Steps to reproduce:

1. place piston
2. break piston
3. ???
4. profit

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: https://seattleschools-my.sharepoint.com/personal/man_ezpommert_seattleschools_org/_layouts/15/guestaccess.aspx?guestaccesstoken=7lrq8b7cbQuqUp4FyQlGfhXsnKcoNl4ZK4gbCwFVV9Q%3d&docid=0463bef85df984df4b6aa6b4499c17ce2&rev=1
- Screenshots: not aplicable/i dont have any

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 5.0.0.2109
- Minecraft: 1.10.2
- Forge: 12.18.2185

**Comment by JCMais** [comment]
Same Issue.

Also, you can keep placing pistons after placing the first one.

**Comment by GirafiStudios** [comment]
This issue was already fixed in https://github.com/Glitchfiend/BiomesOPlenty/commit/7ad2c1c70ed08546abf5d271c2159131dc4588dd , not quite sure why a build didn't come out on CurseForge though. Looks like something broke!

**Comment by Zalaniar** [comment]
I have more information about this issue, which is still happening with the newest versions of forge and BoP. When placing a piston, the number indicator goes down, but the item is not actually removed from the inventory. This can be shown by picking up the stack of pistons (or selecting the "empty" location left by the piston). The count will go up by one. If you do this, when breaking the piston you placed, you only get one back. If you don't move the stack to update the number, when breaking the piston it will appear that you got two pistons since you picked one up which caused the number to update, increasing it by two.

**Comment by xSparky911x** [comment]
Using BoP 2142
Forge 2221 and I still have this bug.
Release with fix coming soon?
